name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Docker image
        run: docker build -t my-express-app .

      - name: Push Docker image to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          docker tag my-express-app railway/app-id/my-express-app
          docker push railway/app-id/my-express-app

      - name: Deploy to Railway
        run: |
          curl -X POST -H "Authorization: Bearer $RAILWAY_TOKEN" \
          -F "image=my-express-app" \
          https://railway.app/api/v1/projects/your-project-id/deployments
